### ISSUE TITLE
Auto-refresh for task status

### ISSUE THREAD

**Issue by sfc-gh-jcarroll** [Yue1Harriet1/rqueue#7]
Hi Harriet Yue,

I came across this repo from the talk at PyData London. I'm on the Streamlit team. This is awesome!!

I saw you are doing refresh() today with a sleep and then rerun exception. I wondered if you considered using `st.experimental_fragment(run_every=)` kwarg for those updates. [Something like this](https://st-experimental-fragment.streamlit.app/Job_status).

Also, is this in a state where you'd be happy for it to be amplified? Someone else on the Streamlit team might be interested to chat :)

Cheers! Thank you for this awesome project!!
Joshua

**Comment by Yue1Harriet1** [comment]
Thanks for your feedback Josh! Let me play some experiments and improve something!!! Cheers

**Comment by sfc-gh-jcarroll** [comment]
Oh one more since you mentioned in your talk - might be interested to talk with @Asaurus1 about https://github.com/Asaurus1/streamlit-process-manager

**Comment by Yue1Harriet1** [comment]
nice thanks for the introduction!

**Comment by Asaurus1** [comment]
Thanks Joshua,

This project looks to be in a very similar vein to SPM but using an external task runner and message broker to handle transactions -- which is honestly probably a lot more reliable than dealing directly with OS processes like SPM does.

If I had to guess, I would be that Yue and I will/have both run into the same issues with the streamlit front-end and the new `fragment` feature that I expressed to you on Discord; essentially that there's there's not a good way to programmatically control just refreshing a part of your app when something changes on the _backend_, and therefore you end up having to either infinitely loop at the end of each script run OR periodically "poll" the _backend_ state in order to see if something changed by rerunning the entire page from top to bottom.

Would definitely be interested to hear your experience, Yue! 👋

**Comment by Yue1Harriet1** [comment]
yayyyyy! what you suggested totally worked for automatic updates @sfc-gh-jcarroll !! :D :D NIceeee , updated the layout_current_session_tasks function in ui_streamlit.py with "run_every" . Sure! would love to chat ! @sfc-gh-jcarroll  👍 :D 💯
